export const UNIVERSES = {
  witcher3: {
    id: 'witcher3',
    title: 'THE WITCHER',
    subtitle: 'The Continent. The Wild Hunt. The Shattering of Lives.',
    tags: ['Characters', 'Factions', 'Lore'],
    accentColor: '#c9a84c',
    enterLabel: 'ENTER THE CONTINENT',
    wakeMessage: 'The Continent stirs. First calls take a moment to answer\u00a0\u2014 the server is waking from its rest.',
    sources: [
      { id: 'game_w3', label: 'WITCHER 3 GAME', desc: 'Wild Hunt + both DLCs. The core experience.' },
      { id: 'game_w1w2', label: 'WITCHER 1 + 2 GAMES', desc: 'Adds backstory. Safe to include alongside W3.' },
      { id: 'books_sapkowski', label: 'SAPKOWSKI BOOKS', desc: 'Original canon. Where everything begins.' },
      { id: 'netflix', label: 'NETFLIX SERIES', desc: 'Adaptation only. Will be clearly labeled when referenced.' },
    ],
    tiers: [
      { id: 'white_orchard', label: 'WHITE ORCHARD', desc: 'Just started. Before Velen.' },
      { id: 'velen_novigrad', label: 'VELEN + NOVIGRAD', desc: "Searching for Ciri's trail." },
      { id: 'skellige', label: 'SKELLIGE + KAER MORHEN', desc: 'Ciri found. Wild Hunt closing in.' },
      { id: 'main_complete', label: 'MAIN STORY COMPLETE', desc: 'Before the DLCs.' },
      { id: 'everything', label: 'EVERYTHING', desc: 'Both DLCs complete. No limits.' },
    ],
    defaultSources: ['game_w3'],
    defaultTier: 'velen_novigrad',
  },
  eldenring: {
    id: 'eldenring',
    title: 'ELDEN RING',
    subtitle: 'The Lands Between. The Shattering. The Erdtree.',
    tags: ['Characters', 'Lore', 'The Shattering'],
    accentColor: '#b8860b',
    enterLabel: 'ENTER THE LANDS BETWEEN',
    wakeMessage: 'The Lands Between stirs. First calls take a moment to answer\u00a0\u2014 the server is waking from its rest.',
    sources: [
      { id: 'game_eldenring', label: 'ELDEN RING', desc: 'Base game. Item descriptions, NPC dialogue, environmental lore.' },
      { id: 'dlc_shadowoftherdtree', label: 'SHADOW OF THE ERDTREE', desc: "DLC. The Land of Shadow and Miquella's fate." },
    ],
    tiers: [
      { id: 'limgrave', label: 'LIMGRAVE', desc: 'Just started. First steps in the Lands Between.' },
      { id: 'liurnia', label: 'LIURNIA + CAELID', desc: 'Past Stormveil. The academy and the rot.' },
      { id: 'altus', label: 'ALTUS PLATEAU + LEYNDELL', desc: 'Approaching the capital. Two shardbearers defeated.' },
      { id: 'mountaintops', label: 'MOUNTAINTOPS + FARUM AZULA', desc: 'The forge. The fall of the Erdtree.' },
      { id: 'main_complete', label: 'MAIN GAME COMPLETE', desc: 'Any ending achieved. Before Shadow of the Erdtree.' },
      { id: 'everything', label: 'EVERYTHING', desc: 'Shadow of the Erdtree complete. No limits.' },
    ],
    defaultSources: ['game_eldenring'],
    defaultTier: 'limgrave',
  },
  dune: {
    id: 'dune',
    title: 'DUNE',
    subtitle: "Arrakis. The spice. The prophecy. The cost of becoming a god.",
    tags: ['Books', 'Films', 'The Imperium'],
    accentColor: '#d4956a',
    enterLabel: 'ENTER THE IMPERIUM',
    wakeMessage: 'The desert stirs. First calls take a moment to answer\u00a0\u2014 the server is waking from its rest.',
    sources: [
      { id: 'book_dune', label: 'DUNE (FRANK HERBERT)', desc: 'The original 1965 novel. Primary canon. Where everything begins.' },
      { id: 'book_messiah', label: 'DUNE MESSIAH', desc: "Second novel. Paul's reckoning. The cost of the holy war." },
      { id: 'book_children', label: 'CHILDREN OF DUNE', desc: 'Third novel. Leto II and the Golden Path.' },
      { id: 'film_2021', label: 'DUNE: PART ONE (2021)', desc: 'Villeneuve adaptation. Faithful to book 1 part 1.' },
      { id: 'film_2024', label: 'DUNE: PART TWO (2024)', desc: 'Villeneuve adaptation. Book 1 part 2, some changes.' },
    ],
    tiers: [
      { id: 'arrakis_arrival', label: 'ARRIVAL ON ARRAKIS', desc: 'Paul arrives. The spice. The desert.' },
      { id: 'fremen', label: 'AMONG THE FREMEN', desc: 'Paul joins the Fremen. Stilgar. Chani.' },
      { id: 'muadib', label: "MUAD'DIB RISES", desc: "Paul becomes Muad'Dib. The holy war begins." },
      { id: 'dune_complete', label: 'DUNE COMPLETE', desc: 'First book or both films complete.' },
      { id: 'messiah', label: 'DUNE MESSIAH', desc: "The cost of the holy war. Paul's fate." },
      { id: 'everything', label: 'EVERYTHING', desc: 'Children of Dune and beyond. No limits.' },
    ],
    defaultSources: ['film_2021', 'film_2024'],
    defaultTier: 'dune_complete',
  },
  lotr: {
    id: 'lotr',
    title: 'LORD OF THE RINGS',
    subtitle: 'Middle-earth. The One Ring. The long defeat.',
    tags: ['Books', 'Films', 'The Silmarillion'],
    accentColor: '#6b8f5e',
    enterLabel: 'ENTER MIDDLE-EARTH',
    wakeMessage: 'Middle-earth stirs. First calls take a moment to answer\u00a0\u2014 the server is waking from its rest.',
    sources: [
      { id: 'book_lotr', label: 'THE LORD OF THE RINGS', desc: 'Tolkien\'s trilogy. The primary canon.' },
      { id: 'book_silmarillion', label: 'THE SILMARILLION', desc: 'The deep history. Creation, the First Age, Númenor.' },
      { id: 'book_hobbit', label: 'THE HOBBIT', desc: 'Bilbo\'s journey. The finding of the Ring.' },
      { id: 'film_fellowship', label: 'THE FELLOWSHIP OF THE RING (2001)', desc: 'Jackson film. First part of the trilogy.' },
      { id: 'film_two_towers', label: 'THE TWO TOWERS (2002)', desc: 'Jackson film. Second part of the trilogy.' },
      { id: 'film_return_king', label: 'THE RETURN OF THE KING (2003)', desc: 'Jackson film. Third part of the trilogy.' },
      { id: 'film_rings_of_power', label: 'RINGS OF POWER (SERIES)', desc: 'Amazon series. Second Age adaptation. Always labeled.' },
    ],
    tiers: [
      { id: 'shire', label: 'THE SHIRE', desc: 'The journey begins. Before Rivendell.' },
      { id: 'rivendell', label: 'RIVENDELL', desc: 'The Council of Elrond. The Fellowship formed.' },
      { id: 'rohan', label: 'ROHAN + HELM\'S DEEP', desc: 'The Fellowship broken. The Rohirrim.' },
      { id: 'gondor', label: 'GONDOR + PELENNOR', desc: 'The siege of Minas Tirith. The Witch-king.' },
      { id: 'lotr_complete', label: 'TRILOGY COMPLETE', desc: 'The Ring destroyed. Aragorn crowned.' },
      { id: 'everything', label: 'EVERYTHING', desc: 'Silmarillion, Hobbit, appendices. No limits.' },
    ],
    defaultSources: ['book_lotr'],
    defaultTier: 'shire',
  },
  got: {
    id: 'got',
    title: 'GAME OF THRONES',
    subtitle: 'Westeros. The Iron Throne. Dragons, politics, and the price of power.',
    tags: ['Books', 'GoT Show', 'House of the Dragon', 'KOTSK'],
    accentColor: '#c0392b',
    enterLabel: 'ENTER WESTEROS',
    wakeMessage: 'Westeros stirs. First calls take a moment to answer\u00a0\u2014 the server is waking from its rest.',
    sources: [
      { id: 'book_asoiaf', label: 'A SONG OF ICE AND FIRE', desc: 'The five published novels. Primary canon. Where everything begins.' },
      { id: 'book_fire_blood', label: 'FIRE & BLOOD', desc: 'History of House Targaryen. The Dance of the Dragons, 170 years before.' },
      { id: 'book_world_of_ice_fire', label: 'THE WORLD OF ICE AND FIRE', desc: 'Illustrated history. Deep worldbuilding and lore.' },
      { id: 'book_dunk_and_egg', label: 'DUNK AND EGG', desc: 'The hedge knight novellas. Ser Duncan and young Egg, 90 years before.' },
      { id: 'show_got_s1_4', label: 'GoT SEASONS 1\u20134', desc: 'Largely faithful to the books with compression. Always labeled.' },
      { id: 'show_got_s5_8', label: 'GoT SEASONS 5\u20138', desc: 'Diverges from books. Always labeled. Not book canon.' },
      { id: 'show_hotd_s1_2', label: 'HOUSE OF THE DRAGON S1\u20132', desc: 'HBO adaptation of Fire & Blood. The Dance of the Dragons, 170 years before GoT.' },
      { id: 'show_kotsk', label: 'A KNIGHT OF THE SEVEN KINGDOMS', desc: 'HBO Dunk and Egg adaptation. Ser Duncan and young Egg, 90 years before.' },
    ],
    tiers: [
      { id: 'kings_landing', label: "KING'S LANDING", desc: "The game begins. Ned Stark arrives." },
      { id: 'war_of_five_kings', label: 'WAR OF FIVE KINGS', desc: 'The realm fractures. Blood on every throne.' },
      { id: 'hotd', label: 'HOUSE OF THE DRAGON', desc: '170 years before. The Targaryen civil war. HotD seasons 1\u20132.' },
      { id: 'red_wedding', label: 'BEYOND THE RED WEDDING', desc: 'The north remembers. Everything changed.' },
      { id: 'dance_of_dragons', label: 'DANY ARRIVES IN WESTEROS', desc: 'Dragons come west. The final war begins.' },
      { id: 'show_complete', label: 'SHOW COMPLETE', desc: 'All eight seasons of GoT watched.' },
      { id: 'everything', label: 'EVERYTHING', desc: 'All books, Fire and Blood, The World of Ice and Fire.' },
    ],
    defaultSources: ['book_asoiaf', 'show_got_s1_4'],
    defaultTier: 'war_of_five_kings',
  },
  starwars: {
    id: 'starwars',
    title: 'STAR WARS',
    subtitle: 'A galaxy far, far away. The Force, the Empire, and the story of the Skywalkers.',
    tags: ['Films', 'The Clone Wars', 'Mandalorian'],
    accentColor: '#4a6fa5',
    enterLabel: 'ENTER THE GALAXY',
    wakeMessage: 'The galaxy stirs. First calls take a moment to answer\u00a0\u2014 the server is waking from its rest.',
    sources: [
      { id: 'film_original_trilogy', label: 'ORIGINAL TRILOGY', desc: 'Episodes IV, V, VI. The foundation.' },
      { id: 'film_prequel_trilogy', label: 'PREQUEL TRILOGY', desc: 'Episodes I, II, III. The fall of the Republic.' },
      { id: 'film_sequel_trilogy', label: 'SEQUEL TRILOGY', desc: 'Episodes VII, VIII, IX. A new generation.' },
      { id: 'film_anthology', label: 'ANTHOLOGY FILMS', desc: 'Rogue One, Solo. Stories between the saga.' },
      { id: 'tv_clone_wars', label: 'THE CLONE WARS', desc: '7 seasons. The war between trilogies.' },
      { id: 'tv_rebels', label: 'REBELS', desc: 'Bridges Clone Wars to the original trilogy.' },
      { id: 'tv_mandalorian', label: 'THE MANDALORIAN', desc: 'After the Empire falls. Grogu. Din Djarin.' },
      { id: 'tv_andor', label: 'ANDOR', desc: 'The making of a rebel. Before Rogue One.' },
      { id: 'legends_kotor', label: 'KNIGHTS OF THE OLD REPUBLIC', desc: 'KOTOR I + II. 4,000 years before the saga.' },
      { id: 'legends_eu_novels', label: 'EXPANDED UNIVERSE NOVELS', desc: 'Thrawn trilogy, New Jedi Order, and more.' },
    ],
    sourceGroups: [
      {
        label: 'FILMS',
        sources: [
          { id: 'film_original_trilogy', label: 'ORIGINAL TRILOGY', desc: 'Episodes IV, V, VI. The foundation.', default: true },
          { id: 'film_prequel_trilogy', label: 'PREQUEL TRILOGY', desc: 'Episodes I, II, III. The fall of the Republic.', default: true },
          { id: 'film_sequel_trilogy', label: 'SEQUEL TRILOGY', desc: 'Episodes VII, VIII, IX. A new generation.', default: false },
          { id: 'film_anthology', label: 'ANTHOLOGY FILMS', desc: 'Rogue One, Solo. Stories between the saga.', default: false },
        ],
      },
      {
        label: 'TV SERIES',
        sources: [
          { id: 'tv_clone_wars', label: 'THE CLONE WARS', desc: '7 seasons. The war between trilogies.', default: true },
          { id: 'tv_rebels', label: 'REBELS', desc: 'Bridges Clone Wars to the original trilogy.', default: false },
          { id: 'tv_mandalorian', label: 'THE MANDALORIAN', desc: 'After the Empire falls. Grogu. Din Djarin.', default: false },
          { id: 'tv_andor', label: 'ANDOR', desc: 'The making of a rebel. Before Rogue One.', default: false },
        ],
      },
      {
        label: 'LEGENDS \u2014 NON-CANON',
        collapsed: true,
        warning: 'Declared non-canon in 2014. Always labeled separately, never mixed with Disney canon.',
        sources: [
          { id: 'legends_kotor', label: 'KNIGHTS OF THE OLD REPUBLIC', desc: 'KOTOR I + II. 4,000 years before the saga.', default: false },
          { id: 'legends_eu_novels', label: 'EXPANDED UNIVERSE NOVELS', desc: 'Thrawn trilogy, New Jedi Order, and more.', default: false },
        ],
      },
    ],
    tiers: [
      { id: 'original_trilogy', label: 'THE ORIGINAL TRILOGY', desc: 'Episodes IV, V, VI. A New Hope through Return of the Jedi.' },
      { id: 'prequel_trilogy', label: 'THE PREQUEL TRILOGY', desc: 'All six saga films. The fall of Anakin Skywalker.' },
      { id: 'clone_wars_era', label: 'THE CLONE WARS ERA', desc: 'Films + Clone Wars complete. Order 66 from every angle.' },
      { id: 'rebellion_era', label: 'THE REBELLION ERA', desc: 'Rebels, Andor, Rogue One. The spark that lit the fire.' },
      { id: 'new_republic_era', label: 'THE NEW REPUBLIC ERA', desc: 'Mandalorian, Ahsoka. After the Empire falls.' },
      { id: 'sequel_trilogy', label: 'THE SEQUEL TRILOGY', desc: 'All nine saga films. The rise and fall of the First Order.' },
      { id: 'everything', label: 'EVERYTHING', desc: 'All canon sources. No limits.' },
    ],
    defaultSources: ['film_original_trilogy', 'film_prequel_trilogy', 'tv_clone_wars'],
    defaultTier: 'clone_wars_era',
  },
}

export function getTierLabel(universe, tierId) {
  const tier = universe.tiers.find(t => t.id === tierId)
  return tier ? tier.label : tierId.toUpperCase()
}
