export const UNIVERSES = {
  witcher3: {
    id: 'witcher3',
    title: 'THE WITCHER 3',
    subtitle: 'The Continent. The Wild Hunt. The Shattering of Lives.',
    tags: ['Characters', 'Factions', 'Lore'],
    accentColor: '#c9a84c',
    enterLabel: 'ENTER THE CONTINENT',
    wakeMessage: 'The Continent stirs. First calls take a moment to answer\u00a0\u2014 the server is waking from its rest.',
    sources: [
      { id: 'game_w3', label: 'WITCHER 3 GAME', desc: 'Wild Hunt + both DLCs. The core experience.' },
      { id: 'game_w1w2', label: 'WITCHER 1 + 2 GAMES', desc: 'Adds backstory. Safe to include alongside W3.' },
      { id: 'books_sapkowski', label: 'SAPKOWSKI BOOKS', desc: 'Original canon. Where everything begins.' },
      { id: 'netflix', label: 'NETFLIX SERIES', desc: 'Adaptation only. Will be clearly labeled when referenced.' },
    ],
    tiers: [
      { id: 'white_orchard', label: 'WHITE ORCHARD', desc: 'Just started. Before Velen.' },
      { id: 'velen_novigrad', label: 'VELEN + NOVIGRAD', desc: "Searching for Ciri's trail." },
      { id: 'skellige', label: 'SKELLIGE + KAER MORHEN', desc: 'Ciri found. Wild Hunt closing in.' },
      { id: 'main_complete', label: 'MAIN STORY COMPLETE', desc: 'Before the DLCs.' },
      { id: 'everything', label: 'EVERYTHING', desc: 'Both DLCs complete. No limits.' },
    ],
    defaultSources: ['game_w3'],
    defaultTier: 'velen_novigrad',
  },
  eldenring: {
    id: 'eldenring',
    title: 'ELDEN RING',
    subtitle: 'The Lands Between. The Shattering. The Erdtree.',
    tags: ['Characters', 'Lore', 'The Shattering'],
    accentColor: '#c4a882',
    enterLabel: 'ENTER THE LANDS BETWEEN',
    wakeMessage: 'The Lands Between stirs. First calls take a moment to answer\u00a0\u2014 the server is waking from its rest.',
    sources: [
      { id: 'game_eldenring', label: 'ELDEN RING', desc: 'Base game. Item descriptions, NPC dialogue, environmental lore.' },
      { id: 'dlc_shadowoftherdtree', label: 'SHADOW OF THE ERDTREE', desc: "DLC. The Land of Shadow and Miquella's fate." },
    ],
    tiers: [
      { id: 'limgrave', label: 'LIMGRAVE', desc: 'Just started. First steps in the Lands Between.' },
      { id: 'liurnia', label: 'LIURNIA + CAELID', desc: 'Past Stormveil. The academy and the rot.' },
      { id: 'altus', label: 'ALTUS PLATEAU + LEYNDELL', desc: 'Approaching the capital. Two shardbearers defeated.' },
      { id: 'mountaintops', label: 'MOUNTAINTOPS + FARUM AZULA', desc: 'The forge. The fall of the Erdtree.' },
      { id: 'main_complete', label: 'MAIN GAME COMPLETE', desc: 'Any ending achieved. Before Shadow of the Erdtree.' },
      { id: 'everything', label: 'EVERYTHING', desc: 'Shadow of the Erdtree complete. No limits.' },
    ],
    defaultSources: ['game_eldenring'],
    defaultTier: 'limgrave',
  },
  dune: {
    id: 'dune',
    title: 'DUNE',
    subtitle: "Arrakis. The spice. The prophecy. The cost of becoming a god.",
    tags: ['Books', 'Films', 'The Imperium'],
    accentColor: '#c4a35a',
    enterLabel: 'ENTER THE IMPERIUM',
    wakeMessage: 'The desert stirs. First calls take a moment to answer\u00a0\u2014 the server is waking from its rest.',
    sources: [
      { id: 'book_dune', label: 'DUNE (FRANK HERBERT)', desc: 'The original 1965 novel. Primary canon. Where everything begins.' },
      { id: 'book_messiah', label: 'DUNE MESSIAH', desc: "Second novel. Paul's reckoning. The cost of the holy war." },
      { id: 'book_children', label: 'CHILDREN OF DUNE', desc: 'Third novel. Leto II and the Golden Path.' },
      { id: 'film_2021', label: 'DUNE: PART ONE (2021)', desc: 'Villeneuve adaptation. Faithful to book 1 part 1.' },
      { id: 'film_2024', label: 'DUNE: PART TWO (2024)', desc: 'Villeneuve adaptation. Book 1 part 2, some changes.' },
    ],
    tiers: [
      { id: 'arrakis_arrival', label: 'ARRIVAL ON ARRAKIS', desc: 'Paul arrives. The spice. The desert.' },
      { id: 'fremen', label: 'AMONG THE FREMEN', desc: 'Paul joins the Fremen. Stilgar. Chani.' },
      { id: 'muadib', label: "MUAD'DIB RISES", desc: "Paul becomes Muad'Dib. The holy war begins." },
      { id: 'dune_complete', label: 'DUNE COMPLETE', desc: 'First book or both films complete.' },
      { id: 'messiah', label: 'DUNE MESSIAH', desc: "The cost of the holy war. Paul's fate." },
      { id: 'everything', label: 'EVERYTHING', desc: 'Children of Dune and beyond. No limits.' },
    ],
    defaultSources: ['film_2021', 'film_2024'],
    defaultTier: 'dune_complete',
  },
  lotr: {
    id: 'lotr',
    title: 'LORD OF THE RINGS',
    subtitle: 'Middle-earth. The One Ring. The long defeat.',
    tags: ['Books', 'Films', 'The Silmarillion'],
    accentColor: '#8a9e6e',
    enterLabel: 'ENTER MIDDLE-EARTH',
    wakeMessage: 'Middle-earth stirs. First calls take a moment to answer\u00a0\u2014 the server is waking from its rest.',
    sources: [
      { id: 'book_lotr', label: 'THE LORD OF THE RINGS', desc: 'Tolkien\'s trilogy. The primary canon.' },
      { id: 'book_silmarillion', label: 'THE SILMARILLION', desc: 'The deep history. Creation, the First Age, Númenor.' },
      { id: 'book_hobbit', label: 'THE HOBBIT', desc: 'Bilbo\'s journey. The finding of the Ring.' },
      { id: 'film_fellowship', label: 'THE FELLOWSHIP OF THE RING (2001)', desc: 'Jackson film. First part of the trilogy.' },
      { id: 'film_two_towers', label: 'THE TWO TOWERS (2002)', desc: 'Jackson film. Second part of the trilogy.' },
      { id: 'film_return_king', label: 'THE RETURN OF THE KING (2003)', desc: 'Jackson film. Third part of the trilogy.' },
      { id: 'film_rings_of_power', label: 'RINGS OF POWER (SERIES)', desc: 'Amazon series. Second Age adaptation. Always labeled.' },
    ],
    tiers: [
      { id: 'shire', label: 'THE SHIRE', desc: 'The journey begins. Before Rivendell.' },
      { id: 'rivendell', label: 'RIVENDELL', desc: 'The Council of Elrond. The Fellowship formed.' },
      { id: 'rohan', label: 'ROHAN + HELM\'S DEEP', desc: 'The Fellowship broken. The Rohirrim.' },
      { id: 'gondor', label: 'GONDOR + PELENNOR', desc: 'The siege of Minas Tirith. The Witch-king.' },
      { id: 'lotr_complete', label: 'TRILOGY COMPLETE', desc: 'The Ring destroyed. Aragorn crowned.' },
      { id: 'everything', label: 'EVERYTHING', desc: 'Silmarillion, Hobbit, appendices. No limits.' },
    ],
    defaultSources: ['book_lotr'],
    defaultTier: 'shire',
  },
  got: {
    id: 'got',
    title: 'GAME OF THRONES',
    subtitle: 'Westeros. The Iron Throne. When you play the game of thrones, you win or you die.',
    tags: ['Books', 'Show', 'ASOIAF'],
    accentColor: '#c0392b',
    enterLabel: 'ENTER WESTEROS',
    wakeMessage: 'Westeros stirs. First calls take a moment to answer\u00a0\u2014 the server is waking from its rest.',
    sources: [
      { id: 'book_asoiaf', label: 'A SONG OF ICE AND FIRE', desc: 'The five published novels. Primary canon. Where everything begins.' },
      { id: 'book_fire_blood', label: 'FIRE & BLOOD', desc: 'History of House Targaryen. The Dance of the Dragons.' },
      { id: 'book_world_of_ice_fire', label: 'THE WORLD OF ICE AND FIRE', desc: 'Illustrated history. Deep worldbuilding and lore.' },
      { id: 'show_s1_4', label: 'SHOW SEASONS 1\u20134', desc: 'Largely faithful to the books with compression. Always labeled.' },
      { id: 'show_s5_8', label: 'SHOW SEASONS 5\u20138', desc: 'Diverges from books. Always labeled. Not book canon.' },
    ],
    tiers: [
      { id: 'kings_landing', label: "KING'S LANDING", desc: "The game begins. Ned Stark arrives." },
      { id: 'war_of_five_kings', label: 'WAR OF FIVE KINGS', desc: 'The realm fractures. Blood on every throne.' },
      { id: 'red_wedding', label: 'BEYOND THE RED WEDDING', desc: 'The north remembers. Everything changed.' },
      { id: 'dance_of_dragons', label: 'DANY ARRIVES IN WESTEROS', desc: 'Dragons come west. The final war begins.' },
      { id: 'show_complete', label: 'SHOW COMPLETE', desc: 'All eight seasons watched.' },
      { id: 'everything', label: 'EVERYTHING', desc: 'All books, Fire and Blood, The World of Ice and Fire.' },
    ],
    defaultSources: ['book_asoiaf', 'show_s1_4'],
    defaultTier: 'war_of_five_kings',
  },
}

export function getTierLabel(universe, tierId) {
  const tier = universe.tiers.find(t => t.id === tierId)
  return tier ? tier.label : tierId.toUpperCase()
}
